services:
  claudecode:
    image: claudehands-local
    user: root  
    build:
      context: .
      dockerfile: Dockerfile_claude_code_sse
    volumes:
      - /home/spenser/__Project_Code/spensermcconnell.com:/workspace
    ports:
      - "9999:9999"
    restart: unless-stopped
    stdin_open: true

  tavily:
    image: tavily-x64
    build:
      context: .
      dockerfile: Dockerfile_tavily_x64
    restart: unless-stopped
    stdin_open: true 
    env_file:
      - .env